// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var API_ENDPOINT, Signifyd, got;

  got = require('got');

  API_ENDPOINT = 'https://api.signifyd.com/v2/cases/';

  Signifyd = (function() {
    function Signifyd(apiKey) {
      this.options = {
        headers: {
          'Authorization': 'Basic ' + new Buffer(apiKey).toString('base64')
        }
      };
    }

    Signifyd.prototype.getAnalysis = function(caseId, callback) {
      return got(API_ENDPOINT + caseId + '/analysis', this.options, function(err, data, res) {
        if (err) {
          console.log(err);
          callback(err, null);
          return;
        }
        return callback(err, JSON.parse(data));
      });
    };

    Signifyd.prototype.getEntries = function(caseId, callback) {
      return got(API_ENDPOINT + caseId + '/entries', this.options, function(err, data, res) {
        if (err) {
          console.log(err);
          callback(err, null);
          return;
        }
        return callback(err, JSON.parse(data));
      });
    };

    Signifyd.prototype.getNotes = function(caseId, callback) {
      return got(API_ENDPOINT + caseId + '/notes', this.options, function(err, data, res) {
        if (err) {
          console.log(err);
          callback(err, null);
          return;
        }
        return callback(err, JSON.parse(data));
      });
    };

    Signifyd.prototype.getOrder = function(caseId, callback) {
      return got(API_ENDPOINT + caseId + '/order', this.options, function(err, data, res) {
        if (err) {
          console.log(err);
          callback(err, null);
          return;
        }
        return callback(err, JSON.parse(data));
      });
    };

    Signifyd.prototype.getScore = function(caseId, callback) {
      return got(API_ENDPOINT + caseId, this.options, function(err, data, res) {
        var responseData;
        if (err) {
          console.log(err);
          callback(err, null);
          return;
        }
        responseData = JSON.parse(data);
        return callback(err, responseData.adjustedScore);
      });
    };

    return Signifyd;

  })();

  module.exports = Signifyd;

}).call(this);
